- platform: tensorflow
  source:
    - entity_id: camera.driveway
  file_out:
    - "/config/www/tensorflow/{{ camera_entity.split('.')[1] }}_latest.jpg"
  model:
    graph: /config/tensorflow/frozen_inference_graph.pb