homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 180
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Friendly Names
  customize: !include customize.yaml

emulated_hue:
  expose_by_default: true
  exposed_domains:
    - light
    - group

http:
  api_password: !secret api_password

frontend:
updater:
discovery:
conversation:
history:
logbook:
sun:
zwave:
  usb_path: /dev/ttyACM0
  autoheal: false

sensor: !include_dir_merge_list sensors/
mqtt: !include mqtt.yaml
automation: !include_dir_list automation/
zone: !include zones.yaml
proximity: !include proximity.yaml
light: !include_dir_merge_list light/
group: !include_dir_merge_named groups/
script: !include_dir_merge_named scripts/

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: True
    waypoint_whitelist:
      - mike
      - christine
      - home

ecobee:
  api_key: !secret ecobee_api_key

notify:
  - name: ecobee
    platform: ecobee
  - name: pushover
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key


