homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 32
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Friendly Names
  customize: !include customize.yaml
  auth_providers:
    - type: legacy_api_password
      api_password: !secret api_password

emulated_hue:
  expose_by_default: true
  listen_port: 80
  exposed_domains:
    - light
    - group

http:
  base_url: 192.168.1.181:8123
api:

tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: /scratch
    time_memory: 57600

frontend:
config:
updater:
discovery:
conversation:
history:
logbook:
sun:
ffmpeg:
map:
system_health:

person: !include_dir_merge_list person/
zwave: !include zwave.yaml
sensor: !include_dir_merge_list sensors/
mqtt: !include mqtt.yaml
automation old: !include_dir_list automation/
automation: !include automations.yaml
zone: !include zones.yaml
proximity: !include proximity.yaml
light: !include_dir_merge_list light/
group: !include_dir_merge_named groups/
script: !include_dir_merge_named scripts/
camera: !include_dir_merge_list cameras/
input_boolean: !include_dir_merge_named components/input_boolean/
# image_processing: !include_dir_merge_list image_processing/

climate:
  platform: zwave

cover:
  - platform: mqtt
    name: "Left Garage Door"
    state_topic: "cover/left_garage_door"
    command_topic: "cover/left_garage_door/set"
  - platform: mqtt
    name: "Right Garage Door"
    state_topic: "cover/right_garage_door"
    command_topic: "cover/right_garage_door/set"

device_tracker:
  # - platform: owntracks
  # - platform: unifi
  #   host: 192.168.1.239
  #   username: !secret unifi_username
  #   password: !secret unifi_password
  #   verify_ssl: false
  #   new_device_defaults:
  #     track_new_devices: false


# owntracks:
#   max_gps_accuracy: 200
#   waypoints: True
#   waypoint_whitelist:
#     - mike

ecobee:
  api_key: !secret ecobee_api_key

arlo:
  username: !secret arlo_username
  password: !secret arlo_password

notify:
  - name: ecobee
    platform: ecobee
  - name: pushover
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key
