homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 180
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Friendly Names
  customize: !include customize.yaml

emulated_hue:
  expose_by_default: true
  listen_port: 80
  exposed_domains:
    - light
    - group

http:
  api_password: !secret api_password
  base_url: 192.168.1.247:8123

tts:
  - platform: google
    cache: true
    cache_dir: /mnt/freenas/media/hass-cache
    time_memory: 57600

frontend:
updater:
discovery:
conversation:
history:
logbook:
sun:
zwave:
  usb_path: /dev/ttyACM0
  autoheal: false
  #config_path: /home/mike/open-zwave-control-panel/

sensor: !include_dir_merge_list sensors/
mqtt: !include mqtt.yaml
automation: !include_dir_list automation/
zone: !include zones.yaml
proximity: !include proximity.yaml
light: !include_dir_merge_list light/
group: !include_dir_merge_named groups/
script: !include_dir_merge_named scripts/
remote: !include_dir_merge_list remotes/

cover:
  - platform: mqtt
    name: "Left Garage Door"
    state_topic: "cover/left_garage_door"
    command_topic: "cover/left_garage_door/set"
  - platform: mqtt
    name: "Right Garage Door"
    state_topic: "cover/right_garage_door"
    command_topic: "cover/right_garage_door/set"

input_boolean: !include_dir_merge_named components/input_boolean/

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: True
    waypoint_whitelist:
      - mike
      - christine
      - home

ecobee:
  api_key: !secret ecobee_api_key

notify:
  - name: ecobee
    platform: ecobee
  - name: pushover
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key


