alias: "Master Bedroom Play Lights On"
trigger:
  platform: state
  entity_id: media_player.bedroom
  to: playing
condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
action:
  service: light.turn_on
  entity_id: group.bedroom_lights_rgb
  data:
    brightness: 255
    rgb_color: [99,0,242]
