alias: "Master Bedroom Media Pause Lights"
trigger:
  platform: state
  entity_id: media_player.bedroom
  to: paused
condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
action:
  service: light.turn_on
  entity_id: group.bedroom_lights_rgb
  data:
    brightness: 255
    rgb_color: [242,169,0]
