- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - icon
    - precip_type
    - precip_intensity
    - precip_probability
    - apparent_temperature
    - humidity
    - minutely_summary
    - hourly_summary
    - daily_summary
    - apparent_temperature_max
    - apparent_temperature_min
    - precip_intensity_max
