alias: "Arriving Home"
trigger:
  - platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
action:
  service: script.notify_pushover
  data:
    message: 'Welcome home!'
