alias: "Attic Flood Detected"
trigger:
  - platform: state
    entity_id: binary_sensor.attic_ac_water_sensor
    from: 'off'
    to: 'on'
action:
  - service: script.notify_pushover
    data:
      message: 'WARNING: Attic flood sensor tripped'
  - service: tts.google_say
    data:
      entity_id: media_player.kitchen_home
      message: 'Warning, Attic flood sensor tripped'
