alias: "Basement Flood Detected"
trigger:
  - platform: state
    entity_id: binary_sensor.basement_water_sensor
    from: 'off'
    to: 'on'
action:
  - service: script.notify_pushover
    data:
      message: 'WARNING: Basement flood sensor tripped'
  - service: tts.google_say
    data:
      entity_id: media_player.kitchen_home
      message: 'Warning, Basement flood sensor tripped'
