alias: "Christine Arriving Home"
trigger:
  - platform: state
    entity_id: device_tracker.christine_christine
    from: 'not_home'
    to: 'home'
  - platform: state
    entity_id: device_tracker.christine_christine
    from: 'Work'
    to: 'home'
condition:
  - condition: state
    entity_id: device_tracker.mike_pixel3
    state: 'home'
action:
  - service: tts.google_say
    data:
      entity_id: media_player.kitchen_home
      message: "Christine is home"
