alias: "Christine left work"
trigger:
  platform: state
  entity_id: device_tracker.christine_christine
  from: 'Work'
  to: 'not_home'
action:
  service: notify.pushover
  data:
    message: 'Christine left work'
