alias: "Everyone left home"
trigger:
  - platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
action:
  service: notify.pushover
  data:
    message: 'Everyone left the house'
