alias: "Family Room Double Tap Off"
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hswd100_wall_dimmer_2
      scene_id: 2
      scene_data: 3
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.living_room_ceiling_light
      scene_id: 2
      scene_data: 3
action:
  service: script.turn_on
  entity_id: script.family_room_lights_off
