alias: "Mike Arriving Home"
trigger:
  - platform: state
    entity_id: device_tracker.mike_mike
    from: 'not_home'
    to: 'home'
  - platform: state
    entity_id: device_tracker.mike_mike
    from: 'Work'
    to: 'home'
action:
  - service: script.notify_pushover
    data:
      message: 'Welcome home, Mike!'
  - service: tts.google_say
    data:
      entity_id: media_player.kitchen_home
      message: 'Mike is home'
