alias: "Mike Arriving Home"
trigger:
  - platform: state
    entity_id: device_tracker.mike_mike
    from: 'not_home'
    to: 'home'
  - platform: state
    entity_id: device_tracker.mike_mike
    from: 'Work'
    to: 'home'
action:
  service: notify.pushover
  data:
    message: 'Welcome home, Mike!'
