alias: "Porch lights on after sunset"
trigger:
  - platform: sun
    event: sunset
    offset: "-00:15:00"
  - platform: numeric_state
    entity_id: proximity.home
    value_template: '{{ states.proximity.home.state | float }}'
    below: 3
  - platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
condition:
  condition: and
  conditions:
    # Only after sunset
    - condition: or
      conditions:
        - condition: sun
          after: sunset
          after_offset: '-0:15:00'
        - condition: sun
          before: sunrise
    - condition: or
      conditions:
        # Either while home or heading home
        - condition: template
          value_template: '{{ states.proximity.home.attributes.dir_of_travel == "towards" and (states.proximity.home.state | float) <= 3 }}'
        - condition: state
          entity_id: group.all_devices
          state: 'home'
action:
  service: script.turn_on
  entity_id: script.porch_lights_on_after_sunset
