alias: "Porch lights on after sunset"
trigger:
  - platform: sun
    event: sunset
    offset: "-00:15:00"
  - platform: numeric_state
    entity_id: proximity.home
    value_template: '{{ states.proximity.home.state | float }}'
    below: 3
  - platform: state
    entity_id: group.mobile_phones
    from: 'not_home'
    to: 'home'
condition:
  condition: and
  conditions:
    # Only after sunset
    - condition: or
      conditions:
        - condition: sun
          after: sunset
          after_offset: '-0:15:00'
        - condition: sun
          before: sunrise
    # If anyone is home
    - condition: or
      conditions:
        - condition: state
          entity_id: group.mobile_phones
          state: 'home'
    # Or if in vacation mode
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.vacation_mode
          state: 'on'
action:
  service: script.turn_on
  entity_id: script.porch_lights_on_after_sunset
