alias: "Porch lights on after sunset"
trigger:
  - platform: sun
    event: sunset
    offset: "-00:15:00"
  - platform: numeric_state
    entity_id: proximity.home
    below: 3
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: group.all_devices
      state: home
    - condition: template
      value_template: '{{ states.proximity.home.attributes.dir_of_travel == "towards" }}'
action:
  service: service.porch_lights_on_after_sunset
